#ifndef ASAACCPPCONSTANTS_HH_
#define ASAACCPPCONSTANTS_HH_

#define ASAAC_MAX_NUMBER_OF_EXCEPTIONS		 	 16
#define OS_TIME_INFINITY_SECONDS				 2147483647
#define OS_TIME_INFINITY_NANOSECONDS			 999999999

#endif /*ASAACCPPCONSTANTS_HH_*/
